<?php

use Illuminate\Database\Seeder;

class CoureregistrationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

       // \DB::table('coureregistrations')->delete();
        
        \DB::table('coureregistrations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 3,
                'lecturer_id' => 1,
                'indexnumber' => 'GES11112',
                'level' => 'Level 100',
                'cource_code' => 'BGEC100',
                'cource_title' => 'Business Management 1',
                'credithours' => '3',
                'IA_mark' => '20',
                'exams_mark' => '40',
                'total_marks' => '60',
                'grade' => 'C+',
                'grade_point' => '2',
                'total_gp' => '6',
                'semester' => 'First Semester',
                'session' => 'Morning Session',
                'academic_year' => '2020-2021',
                'status' => '1',
                'resit' => '0',
                'fvrt' => '1',
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 3,
                'lecturer_id' => NULL,
                'indexnumber' => 'GES11112',
                'level' => 'Level 100',
                'cource_code' => 'BGEC101',
                'cource_title' => 'Business Law ',
                'credithours' => '3',
                'IA_mark' => NULL,
                'exams_mark' => NULL,
                'total_marks' => NULL,
                'grade' => NULL,
                'grade_point' => NULL,
                'total_gp' => NULL,
                'semester' => 'First Semester',
                'session' => 'Morning Session',
                'academic_year' => '2020-2021',
                'status' => NULL,
                'resit' => '0',
                'fvrt' => '0',
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 3,
                'lecturer_id' => NULL,
                'indexnumber' => 'GES11112',
                'level' => 'Level 100',
                'cource_code' => 'BGEC102',
                'cource_title' => 'Intro to Computer Skills',
                'credithours' => '3',
                'IA_mark' => NULL,
                'exams_mark' => NULL,
                'total_marks' => NULL,
                'grade' => NULL,
                'grade_point' => NULL,
                'total_gp' => NULL,
                'semester' => 'First Semester',
                'session' => 'Morning Session',
                'academic_year' => '2020-2021',
                'status' => NULL,
                'resit' => '0',
                'fvrt' => '0',
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 3,
                'lecturer_id' => NULL,
                'indexnumber' => 'GES11112',
                'level' => 'Level 100',
                'cource_code' => 'BGEC103',
                'cource_title' => 'Business Statisties',
                'credithours' => '3',
                'IA_mark' => NULL,
                'exams_mark' => NULL,
                'total_marks' => NULL,
                'grade' => NULL,
                'grade_point' => NULL,
                'total_gp' => NULL,
                'semester' => 'First Semester',
                'session' => 'Morning Session',
                'academic_year' => '2020-2021',
                'status' => NULL,
                'resit' => '0',
                'fvrt' => '0',
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 3,
                'lecturer_id' => NULL,
                'indexnumber' => 'GES11112',
                'level' => 'Level 100',
                'cource_code' => 'BGEC104',
                'cource_title' => 'Communication Skills',
                'credithours' => '3',
                'IA_mark' => NULL,
                'exams_mark' => NULL,
                'total_marks' => NULL,
                'grade' => NULL,
                'grade_point' => NULL,
                'total_gp' => NULL,
                'semester' => 'First Semester',
                'session' => 'Morning Session',
                'academic_year' => '2020-2021',
                'status' => NULL,
                'resit' => '0',
                'fvrt' => '0',
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 3,
                'lecturer_id' => 1,
                'indexnumber' => 'GES11112',
                'level' => 'Level 100',
                'cource_code' => 'BGEC109',
                'cource_title' => 'Principles of Marketing',
                'credithours' => '3',
                'IA_mark' => '10',
                'exams_mark' => '46',
                'total_marks' => '56',
                'grade' => 'C',
                'grade_point' => '1.5',
                'total_gp' => '4.5',
                'semester' => 'Second Semester',
                'session' => 'Morning Session',
                'academic_year' => '2020-2021',
                'status' => '1',
                'resit' => '0',
                'fvrt' => '0',
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 3,
                'lecturer_id' => NULL,
                'indexnumber' => 'GES11112',
                'level' => 'Level 100',
                'cource_code' => 'BGEC110',
                'cource_title' => 'Business Communication  11',
                'credithours' => '3',
                'IA_mark' => '33',
                'exams_mark' => '33',
                'total_marks' => '66',
                'grade' => 'B-',
                'grade_point' => '2.5',
                'total_gp' => '7.5',
                'semester' => 'Second Semester',
                'session' => 'Morning Session',
                'academic_year' => '2020-2021',
                'status' => NULL,
                'resit' => '0',
                'fvrt' => '0',
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 3,
                'lecturer_id' => NULL,
                'indexnumber' => 'GES11112',
                'level' => 'Level 100',
                'cource_code' => 'BGEC106',
                'cource_title' => 'Business Communication 1',
                'credithours' => '3',
                'IA_mark' => NULL,
                'exams_mark' => NULL,
                'total_marks' => NULL,
                'grade' => NULL,
                'grade_point' => NULL,
                'total_gp' => NULL,
                'semester' => 'Second Semester',
                'session' => 'Morning Session',
                'academic_year' => '2020-2021',
                'status' => NULL,
                'resit' => '0',
                'fvrt' => '0',
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 3,
                'lecturer_id' => NULL,
                'indexnumber' => 'GES11112',
                'level' => 'Level 100',
                'cource_code' => 'BGEC107',
                'cource_title' => 'Intro to Organisation Behaviour',
                'credithours' => '3',
                'IA_mark' => NULL,
                'exams_mark' => NULL,
                'total_marks' => NULL,
                'grade' => NULL,
                'grade_point' => NULL,
                'total_gp' => NULL,
                'semester' => 'Second Semester',
                'session' => 'Morning Session',
                'academic_year' => '2020-2021',
                'status' => NULL,
                'resit' => '0',
                'fvrt' => '0',
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 3,
                'lecturer_id' => NULL,
                'indexnumber' => 'GES11112',
                'level' => 'Level 100',
                'cource_code' => 'BGEC108',
                'cource_title' => 'Elements of Economics',
                'credithours' => '3',
                'IA_mark' => NULL,
                'exams_mark' => NULL,
                'total_marks' => NULL,
                'grade' => NULL,
                'grade_point' => NULL,
                'total_gp' => NULL,
                'semester' => 'Second Semester',
                'session' => 'Morning Session',
                'academic_year' => '2020-2021',
                'status' => NULL,
                'resit' => '0',
                'fvrt' => '0',
            ),
        ));
        
        
    }
}